try {
  throw 'ERRO'
} catch {
  console.log('Entrou no catch')
}